### PR TITLE
Datalib related improvements

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by kanitw** [comment]
We shouldn’t remove `lib/datalib.js` because `index.html` is referring to it.  

We can refer to `datalib.js` via `node_modules/datalib/datalib.js` but we also need to modify publish.sh to publish `node_modules/datalib/` to gh-pages.

**Comment by kanitw** [comment]
Other than that.  This PR looks good.

**Comment by domoritz** [comment]
@kanitw True but I removed that it actually needs it. Fixed in d7d43e5

**Comment by kanitw** [comment]
Okay.  Make sense.  Thanks.

**Pull request merged**
