### PR TITLE
bar positioning 

### LINKED ISSUE #388: Log Broken with Bar
should fix by either fixing min for log scale at 1   or must set x/y value to the min value of the scale (is there a way to do that in vega?)

pole

### PR DESCRIPTION
**Pull request by kanitw**
- fixes #388  -- log broken with bar (set `y2 = {group:'height'}`, and `x2= {value:0}`) + unit test
- add offset for single bar + unit test
- also set serve task to use google chrome

### CODE REVIEW

**Comment by domoritz** [comment]
You should use the latest master. It fixes the build.

**Comment by domoritz** [comment]
Still not perfect. 

```json
{
  "marktype": "bar",
  "enc": {
    "x": {"type": "O","name": "Origin"},
    "y": {"scale": {"type": "log"},"type": "Q","name": "Acceleration","aggr": "avg"}
  },
  "data": {"url": "data/cars.json"}
}
```

screen shot 2015-05-21 at 23 34 54

**Comment by kanitw** [comment]
@domoritz  What do you mean still not perfect?   This solves the problem in https://github.com/uwdata/vega-lite/issues/388.

**Comment by domoritz** [comment]
I should have been re specific. What I mean is that the y range should only go to 20, not 100.

**Comment by kanitw** [comment]
That's a different issue.

**Comment by kanitw** [comment]
Also I think it goes to 100 due to `nice` function's behavior so I don't think it's an issue we need to fix here  (unless you come up with a more objective `nice` function).

**Comment by domoritz** [comment]
Agree

**Pull request merged**
